# --------------------------------------------------------------------------
#                               General options                             
# --------------------------------------------------------------------------

enable_web = true
use_https = false

# -------------------------------------------------------------------------- 
#                                    Users                                   
# -------------------------------------------------------------------------- 

[[user]]
username = "test"
password_hash = "$2a$14$JLlXcmp7CVlumK7.83jrHOmBt3le/cjfFQOGuoYaIcYCjILaO81Ti"

[[user]]
username = "test2"
password = "test2"

# --------------------------------------------------------------------------
#                                   Shares                                  
# --------------------------------------------------------------------------

# --------------------------------- Share 1 --------------------------------

[[share]]
name = "test"
path = "/home"

[share.access]
read_write = ["test"]
read = ["test2"]

# --------------------------------- Share 2 --------------------------------

[[share]]
name = "test2"
path = "/tmp"
# Without access section, it's r/w for everyone
